export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'

export const GET_APPOINT = 'GET_APPOINT'
export const GET_APPOINT_FAIL = 'GET_APPOINT_FAIL'
export const GET_APPOINT_SUCCESS = 'GET_APPOINT_SUCCESS'


export const GET_PATIENT = 'GET_PATIENT'
export const GET_PATIENT_FAIL = 'GET_PATIENT_FAIL'
export const GET_PATIENT_SUCCESS = 'GET_PATIENT_SUCCESS'


export const ADD_DOCTOR = 'ADD_DOCTOR'
export const ADD_DOCTOR_FAIL = 'ADD_DOCTOR_FAIL'
export const ADD_DOCTOR_SUCCESS = 'ADD_DOCTOR_SUCCESS'